### ISSUE TITLE
ATE of zero for frontdoor adjustment example

### ISSUE THREAD

**Issue by mullachv** [ijmbarr/notes-on-causal-inference#1]
In function
```
estimate_ate_frontdoor(df,x,y,zs)
```

when called:
```
ds = fd0.sample(10000)
print("Estimated ATE (frontdoor adj: {:.3f})"
      .format(
          estimate_ate_frontdoor(ds,'x','y',['z']))
     )
```
returns an ATE of zero

I modified the code to test out a few things, I shall set it back and capture the results once again

**Comment by ijmbarr** [comment]
Hi @mullachv - can you send me the output of running

`$ pip freeze`

so that I can try and replicate the issue.

**Comment by mullachv** [comment]
Hi @ijmbarr 
I got back to this after being away for a few days. I restarted my jupyter notebook and reran all the cells. I do not notice the case where the computed ATE value is 0.00.

In order to make better sense of ```p_y_xz``` (for myself), 
I am going to simplify it to three nested loops, and I shall see how things turn out. Thank you

**Comment by mullachv** [comment]
@ijmbarr 
I rewrote this:
```
     p_z_x = {
         (x_, z_): np.mean( df.loc[lambda pf: pf[x] == x_][zs].values == z_  )
         for x_ in (0,1)
         for z_ in zs_unique
     }
    
```
as:

```
    p_z_x = {}
    for x_ in [0,1]:
        pf = df[df.x == x_]
        for z_ in zs_unique:
            p_z_x[(x_, z_)] = np.mean(pf[zs].values == z_)

```

```p_y_xz``` is a bit trickier

**Comment by ijmbarr** [comment]
Hi @mullachv 

Looking back at my code, I was probably trying to jam too much on one line. Your version is clearer - and should be possible to extend it the conditional p(Y|XZ):

```python
    p_y_xz = {}
    for x_ in [0,1]:
        df_x_filtered = df[(df[x].values == x_)]
        for z_ in zs_unique:
            # we have to filter these values slightly differently because `zs` 
            # can potentially contain multiple columns. These means that 
            # `.values` returns a matrix - we can still use this to check equality, 
            # but we need to use np.all(..., axis=1) to reduce it to a 1d array for
            # filtering the dataframe.
            df_xz_filtered = df_x_filtered[
                np.all( (df_x_filtered[zs].values == z_), axis=1)
            ]
            for y_ in y_unique:
                p_y_xz[(x_, y_, z_)] = np.mean( df_xz_filtered[y].values == y_ )
```

Let me know if that makes sense.

**Comment by mullachv** [comment]
@ijmbarr Yes, that is definitely helpful for me. Thank you very much for the explanatory comments as well.
